name: continuos Integration-FE
on:
  pull_request:
    branches:
      ['main']

jobs:
    continuos Integration-FE:
            runs-on: ubuntu-latest

    steps:
        - name: Using Node.js
        - uses: actions/checkout@v4
          uses: actions/setup-node@v2
          with:
          node-version: 16.x
         - name: run install, build and test
          run: |
            npm install
            npm run build 
            npm run test